name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to github packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: set environment variable
        run: echo "REPO_OWNER=${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]' " >> ${{ github }}
      
      - uses: actions/checkout@v2
      
      - run: |
          echo "initialized by ${{ github.actor }}" 
        
      - name: build docker image
        run: docker build -t docker.pkg.github.com/${{ github.REPO_OWNER }}/${{ github.repository. }}/${{ github.repository.name }}:1.0.3 .
      - name: push image to github package
        run: docker push docker.pkg.github.com/${{ github.repository }}/${{ github.repository.name }}:1.0.3
