name: ci

on:
  push:
    tags:
    - '*'
    
#     branches:
#       - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to github packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2
      
      - name: Set repo owner and repo name in env vars
        env:
          REPO_OWNER_NAME: ${{ github.repository }}
        run: |
          REPO_OWNER=$(echo "$REPO_OWNER_NAME" | awk '$1=$1' FS="/" OFS=" " | awk '{ print $1}' | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
          echo {{ env.REPO_OWNER }}
          REPO_NAME=$(echo "$REPO_OWNER_NAME" | awk '$1=$1' FS="/" OFS=" " | awk '{ print $2}')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME"
    
      - name: Set released tag in env vars
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: test uat
        if: (${{ env.RELEASE_VERSION }} | grep -E "*-uat$")
        run: |
          echo "inside uat"
          
      - name: test prod
        if: (${{ env.RELEASE_VERSION }} | grep -E "*-production$")
        run: |
          echo "inside prod"

      
#       - name: Print release version
#         run: |
#           echo $RELEASE_VERSION
#           echo ${{ env.RELEASE_VERSION }}
          
#       - name: Display all env variables
#         env:
#           ALL_ENV: ${{ toJSON(env) }}
#         run: echo "$ALL_ENV"
        
      
#       - run: |
#           echo "initialized by ${{ github.actor }}" 
        
#       - name: build docker image
#         run: |
#           pwd
#           ls -al
#           docker build -t docker.pkg.github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}:${{ env.RELEASE_VERSION }} .
#       - name: push image to github package
#         run: docker push docker.pkg.github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}:${{ env.RELEASE_VERSION }}
