name: ci

on:
  push:
    tags:
    - '*'
#     branches:
#       - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to github packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2
    
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Print release version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      
      - run: |
          echo "initialized by ${{ github.actor }}" 
        
      - name: build docker image
        run: docker build -t docker.pkg.github.com/t2wil/hello-github-container-registry/hello-git-actions:${{ env.RELEASE_VERSION }} .
      - name: push image to github package
        run: docker push docker.pkg.github.com/t2wil/hello-github-container-registry/hello-git-actions:${{ env.RELEASE_VERSION }}
