name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to github packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: |
          echo "GITHUB_ACTOR = ${{ github.actor }}" 
        
#       - name: build docker image
#         run: docker build -t docker.pkg.github.com/t2wil/hello-github-container-registry/hello-git-actions:1.0.2 .
#       - name: push image to github package
#         run: docker push docker.pkg.github.com/t2wil/hello-github-container-registry/hello-git-actions:1.0.2

